### ISSUE TITLE
Retrieve more than one message

### ISSUE THREAD

**Issue by donpwinston** [siemens/tstomp#14]
How do I tell it to give me more than the first message on the queue?
The following gives me the first message but then the queue is drained:

package require tStomp

#tStomp::setDebugCmd {}

tStomp s stomp://admin:activemq@localhost:61613
s connect {set ::connected true}
vwait connected

puts "Dequeuing"

set tid [after 2000 {s unsubscribe "/queue/SampleQueue"; puts "timeout"; exit 1}]
s subscribe "/queue/SampleQueue" {	
	array set M $messageNvList
	set ::messagebody $M(messagebody)
} {ack client}
vwait messagebody
after cancel $tid

puts $messagebody

#s unsubscribe "/queue/SampleQueue"

**Comment by muenchhausen** [comment]
Sorry I did not see these questions. I think that your Tcl script just runs to the end and exits (?)
If so, a solution is to write "vwait forever" in the end of your script: Then the Tcl event loop will still handle incomming new messages and call your handlers. E.g.:

package require tStomp
tStomp s stomp://admin:activemq@localhost:61613
s connect {set ::connected true}
vwait connected
s subscribe "/queue/SampleQueue" { puts "new message" }
vwait forever
